### ISSUE TITLE
Dear author:

### ISSUE THREAD

**Issue by zhipengliux** [gaospecial/ccgraph#1]
I try to do this, can ccgraph do it?
![image](https://user-images.githubusercontent.com/71112013/203919889-f782be5c-e65b-46fc-abd1-3c4115cd240f.png)
![image](https://user-images.githubusercontent.com/71112013/203920216-d9b29af2-6e03-4e93-8481-e4ffa71dbd6f.png)

**Comment by gaospecial** [comment]
I am afraid not.
